FROM jdk-j9:latest
MAINTAINER sunpp

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo Asia/Shanghai > /etc/timezone

ARG servicename
RUN mkdir /usr/local/apps
RUN mkdir /usr/local/logs

COPY ./prolog-$servicename-service.jar /usr/local/apps

#COPY $servicename.sh /usr/local/

#VOLUME /usr/local/services:/usr/local/services
#VOLUME /usr/local/services/logs:/usr/local/services/logs

WORKDIR /usr/local
ENV PATH=$PATH:/usr/local/lib
#RUN mv /usr/local/$servicename.sh /usr/local/Entrypoint.sh
